spring.application.name=LabourLinkBackend


##Database configuration
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:sqlserver://cloud-db-intelli5.database.windows.net:1433;database=labourlink;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#spring.datasource.username=Intelli5
#spring.datasource.password=group04IT
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
##server.port=1000

#Database configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://bwlfsr6b0mrhhh0ri3ap-mysql.services.clever-cloud.com:3306/bwlfsr6b0mrhhh0ri3ap
spring.datasource.username=ut0xc2vcaazkk109
spring.datasource.password=iAqmdUGnFGk9lm2kTXKK
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#server.port=1000

#Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=luxshan.thuraisingam@gmail.com
spring.mail.password=oojo dozp dnkd ehnd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#app.firebase-configuration-file=labourlink-1dd8e-firebase-adminsdk-aryqm-03f92bb725.json