spring.application.name=LabourLinkBackend

##pring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/New_Labourlink_Backend
#spring.datasource.username=root
#spring.datasource.password=SuhiBala*12
#spring.jpa.database=mysql
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.show-sql=true
#server.port=1000
#Database configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/labourlink
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

#Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=luxshan.thuraisingam@gmail.com
spring.mail.password=oojo dozp dnkd ehnd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#app.firebase-configuration-file=labourlink-1dd8e-firebase-adminsdk-aryqm-03f92bb725.json